title: 紅樓夢 - 吳淡如
description: 紅樓夢 - 吳淡如
time: Mon, 26 Aug 2024 06:20:14 +0000
items:
  - title: 00. 楔子
    size: 8304080
    duration: 424
  - title: 01. 黛玉入榮國府投靠外祖母
    size: 16982026
    duration: 882
  - title: 02. 寶玉夢遊太虛幻境遇仙姑
    size: 10141126
    duration: 907
  - title: 03. 鳳姐對劉姥姥伸援手
    size: 7269441
    duration: 662
  - title: 04. 寶玉秦鐘一見如故
    size: 9432691
    duration: 859
  - title: 05. 寶玉黛玉探望病中寶釵
    size: 10704761
    duration: 976
  - title: 06. 賈政訓勉寶玉力求上進
    size: 3650091
    duration: 336
  - title: 07. 王熙鳳巧設陷阱斷送賈瑞性命
    size: 11477338
    duration: 1075
  - title: 08. 鳳姐兼管寧國府
    size: 10314030
    duration: 950
  - title: 09. 榮國府為賈妃晉封興建新園
    size: 6307025
    duration: 580
  - title: 10. 賈妃回娘家省親同遊大觀園
    size: 5453108
    duration: 504
  - title: 11. 寶玉約法三章挽留襲人
    size: 8373560
    duration: 773
  - title: 12. 命中的天魔星
    size: 7050288
    duration: 643
  - title: 13. 史湘雲拜訪大觀園
    size: 8958285
    duration: 817
  - title: 14. 寶釵生日看戲惹風波
    size: 4935445
    duration: 453
  - title: 15. 寶玉黛玉偷讀西廂記
    size: 9742237
    duration: 902
  - title: 16. 黛玉欲入怡紅院被拒
    size: 4776224
    duration: 441
  - title: 17. 黛玉葬花寶玉訴心聲
    size: 6892886
    duration: 624
  - title: 18. 寶玉黛玉日日為小事冷戰
    size: 6542429
    duration: 594
  - title: 19. 晴雯撕扇金釧兒投井
    size: 7966313
    duration: 729
  - title: 20. 賈政杖打寶玉
    size: 8123077
    duration: 757
  - title: 21. 寶玉傳手帕表心思
    size: 5609632
    duration: 350
  - title: 22. 劉姥姥逛大觀園
    size: 15935730
    duration: 995
  - title: 23. 鳳姐生日賈璉趁機偷情
    size: 13060176
    duration: 816
  - title: 24. 薛蟠調戲柳湘蓮
    size: 10887201
    duration: 680
  - title: 25. 海棠詩社雪中吟詩
    size: 14409763
    duration: 900
  - title: 26. 探春暫時接管榮國府
    size: 11720615
    duration: 732
  - title: 27. 一句玩笑惹出寶玉瘋病
    size: 13125378
    duration: 820
  - title: 28. 寶玉生日群芳共度
    size: 7342909
    duration: 458
  - title: 29. 賈連瞞鳳姐金屋藏嬌
    size: 16948449
    duration: 1059
  - title: 30. 癡心尤三姐絕望自盡
    size: 6259976
    duration: 391
  - title: 31. 王熙鳳耍心機逼死尤二姐
    size: 15180067
    duration: 948
  - title: 32. 大觀園全部都不對勁了
    size: 11107053
    duration: 694
  - title: 33. 這曖昧的東西是誰的？
    size: 13309698
    duration: 831
  - title: 34. 公主脾氣奴才命
    size: 9580660
    duration: 598
  - title: 35. 傻瓜薛蟠娶了最彪悍的老婆
    size: 6922868
    duration: 432
  - title: 36. 賈寶玉到底該娶誰？
    size: 11181448
    duration: 698
  - title: 37. 賈寶玉，你好狠！林黛玉焚詩斷情緣
    size: 15162105
    duration: 947
  - title: 38. 新嫁娘寶釵憂患多
    size: 10802775
    duration: 675
  - title: 39. 這下惹禍了！榮寧兩府終被抄家
    size: 10531113
    duration: 658
  - title: 40. 完結篇：浮生若夢，落得雪茫茫一片真乾淨！
    size: 6713902
    duration: 419
